parameters:
#    geekhub_user.example.class: Geekhub\UserBundle\Example

services:
#    geekhub_user.example:
#        class: %geekhub_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
